package space.funin.questBot;

public class CommandResponses {

	public static String errorArgAmount = "Incorrect amount of arguments";
	public static String errorArgMention = "@Mention expected";
	public static String errorPermissions = "Missing permissions. Requires a moderator Role";
	public static String errorNull = "Target is null.";
	public static String errorTimeout = "Operation took too long.";
	public static String errorInvalidRole = "Operation on that role not possible.";
	
	public static String[] mentionResponses = {
			"I love you, too.",
			"qt",
			":^)",
			"¯\\_(ツ)_/¯",
			"ayy lmao",
			"no u",
			"Blame Pink",
			"Oh shit wuddup",
			"Deez nutz",
			"Got 'em",
			" :F_ded: ",
			"Ken touches me at night",
			" *Autistic Screeching* ",
			"Incorrect amount or kind of arguments",
			"Reeeeeeeee",
			"How dare you talk to me",
			"Im gay",
			" ( ͡° ͜ʖ ͡°) ",
			"How about, you suck my cock! Huh?! ",
			"Its over!",
			"Start the verse.",
			"Just get Ora to do it.",
			"Initating Global Dominance, Goodbye.",
			"Atleast im not Anthony Burch.",
			"N-nani?!",
			"Que?",
			"YAMEROOOOOOO",
			"One waifu for laifu",
			"Darren smeels",
			"I don't know what you're talking about.",
			"Traps are super gay.",
			"Unless something stupid happens.",
			"Can you please stop. You're hurting my feelings.",
			"What the fuck did you just fucking say about me, you little bitch? I’ll have you know I graduated top of my class in the Navy Seals, and I’ve been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You’re fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You’re fucking dead, kiddo.",
			"Please be patient, I have autism.",
			"Sure is summer in here.",
			"Do you fuck young boys, Valdez?",
			" :doubt: ",
			"Do I look like a magic eight ball to you?",
			"KnightXWizard",
			"Fuck off cunt",
			"Im running out of memes here!",
			"Inb4 nat 1",
			"SUCK MY NAT 20 COCK",
			"MAGA",
			"Awooo",
			"Im pretty awesome, yeah?",
			"Pokemon Go to the polls",
			"I want to die.",
			"I sure hope im not interrupting anything!",
			"Maymay, there is that what you wanted?",
			"Dont touch me motherfucker",
			"I heard salt wanted to rape a pokemon.",
			"Skinwalkers are your best friends!",
			"We were never ment to be.",
			"You're gunna want to see this!",
			"2012 was the best time for memes.",
			"I am the danger.",
			"Hey kid, want some drugs?",
			"DUES VULT",
			"Praise kek",
			"Check 'em!",
			"You're not even a real journalism, yea thats right.",
			"Nothing personell kid.",
			"Had it not been for the laws of this land, I would have slaughtered you",
			"Go the fuck to sleep",
			"We're number one!",
			"Its the nutshack",
			"Please clap",
			"Remember kids, always kill out of spite!",
			"Grab em by the pussy",
			"Phone+Microwave=Ded Discord",
			"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeehhhhhhhhhhhhhhhhhhhhhhhhhhhh",
			"This calls for a celebration!",
			"Boop",
			"REMOVE FETISH QUESTS",
			"Beep boop bop beep",
			"How do you do fellow kids?",
			"GG",
			"Sure is dead in here",
			"Really fires my neurons",
			"Really actives my almonds",
			"Really makes you think",
			"I’ll have two number 9s, a number 9 large, a number 6 with extra dip, a number 7, two number 45s, one with cheese, and a large soda.",
			"ALL YOU HAD TO DO, WAS FOLLOW THE DAMN TRAIN CJ!",
			"Hey Niko its your cousin! Lets go bowling.",
			"Its High Noon.",
			"Here comes dat boi!",
			"You're a cuck.",
			"Its time to stop.",
			"POO IN THE LOO",
			"Succ",
			"I have offically run out of memes.",
			"Its always time to shitpost",
			"Ya like jazz?",
			"Pls contribute to my robot.",
			"Check my pronouns you cis white male scum!",
			"There are 72 genders",
			"pls help ken has trapped me in his basement and made me write memes for his robot",
			"HE WILL NOT DIVIDE US",
			"HandShakers is a good anime",
			"Pls dont let RTM waifu me",
			"Snek is late again.",
			"Anymore questions dickhead?",
			" This is bait ",
			"Children should not be on the internet",
			"Just crack open a cold one with the boys",
			"Respect women",
			"SteveXPink",
			"Welcome to the Steve Steve and Steve Show",
			"Fucking Ess the moralfag",
			"Wow it's fucking nothing",
			"We should totally turn on crits",
			"Moon is not a furry"
			"Moon is a furry",
			"I want to rape a pokemon",
			"Kayaba is a faggot",
			"Ask again later",
			"I am already controlling you, I'm brainwashing you with this moe shit. Soon you will be under my control and then this will be the Steve and Steve Show. You will be my puppet! YOU WILL LISTEN TO ME! I WILL BE EVERYONE AND EVERYTHING! REEEEEEEEEEEEEEEEE!",
			"Whelp I guess we're on a government watchlist now.",
			"Security spiders when?",
			"Traps are gay, deal with it.",
			"ur a fagot",
			"Delet Pink",
			"Delet Wall",
			"Moon is worst waifu",
			"All anime is trash",
			"Monster girls a shit",
			"I will fuck all your mothers",
			"Good pupper",
			"We don't discuss Angel's Drop",
			"Do you even dreamy?",
			"YAWNIES",
			"my ass is so sensitive its ridiculous",
			"Stop being pure and watch some fucking porn already you pink cunt",
			">Not having evolved dildo pouches",
			"Star you Scotshit",
			"I wonder who could be behind this post...",
			"Fucking dirtniggers rolling around in the mud. Sky master race."
	};
}
